services:
  openbin:
    container_name: openbin
    image: openbin:latest
    build: .
    ports:
      - "${HOST_PORT:-1453}:1453"
    env_file: .env
    environment:
      DATABASE_PATH: /data/openbin.db
      PHOTO_STORAGE_PATH: /data/photos
      BACKUP_PATH: /data/backups
    volumes:
      - api_data:/data

volumes:
  api_data:
